variables: 
    #SCHEDULER_PARAMETERS: "-C gpu -N 1 -t 00:10:00 -c 10 -G 1 -A m3767"
    #SCHEDULER_PARAMETERS: "-C haswell --qos shared -N 1 -n 4 -c 4 -A mp111 -t 00:02:00"
    #Cori Compile
    SCHEDULER_PARAMETERS: "-M escori -q compile -n 16 -t 00:10:00"




.ci-runner:
    tags:
        - cori

.common_build:
    extends: .ci-runner
    before_script:
        - module swap PrgEnv-intel PrgEnv-gnu
        - module load cray-fftw
    interuptable: true    


stages: 
  - pull
  - merge
  - test

pull:
  stage: pull
  script: 
    - echo "This is where you pull from GitHub."
  interuptable: true

merge:
  stage: merge
  script: 
    - echo "This is where you merge branch into main."
  interuptable: true
      

test:
  stage: test
  extends:
    - .common_build
  script:
    - echo "This is where you compile things."
  interuptable: true

