name: Like Pizza

on: 
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ (github.event.comment.body == 'I like strings') && contains( 'etpalmer63', github.event.comment.user.login) }}
    steps:
      - name: Like Pizza
        uses: actions/github-script@v4
        with: 
          script:  |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Initiated Cori Compilation',
            });
      - uses: actions/checkout@v2
      - name: output GitHub API
        run: .github/workflows/id_most_recent_comment_on_PR.sh ${{secrets.GITLAB_TRIGGER_TOKEN}}

