name: Like Pizza

on: 
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    env:
      USER_LIST: ${{ secrets.AUTH_LIST }} 
      TRIGGER_STRING: 'I like strings'  
        #USER_LIST: 'JohnDoe etpalmer63 JaneDoe jmsexton03'
      #    #if: ${{ (github.event.comment.body == 'I like pizza') && contains( "etpalmer63", github.event.comment.user.login) }}
    steps:
      - name: Like Pizza
        #if: ${{ (github.event.comment.body == 'I like cats') && contains( env.AUTH_LIST, github.event.comment.user.login) }}
        #if: ${{ (github.event.comment.body == 'I like cats') && contains( env.USER_LIST, github.event.comment.user.login) }}
        if: ${{ (github.event.comment.body == env.TRIGGER_STRING) && contains( env.USER_LIST, github.event.comment.user.login) }}
        uses: actions/github-script@v4
        with: 
          script:  |
            github.event.payload.node_id | jc -r 
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Initiated Cori Compilation',
            });

      - name: trigger job
        uses: wei/curl@v1 
        with:  
          #args: -X POST -F token=${{secrets.GITLAB_TRIGGER_TOKEN}} https://software.nersc.gov/api/v4/projects/307/pipeline?ref=main
          #args: -X POST -F token=${{secrets.GITLAB_TRIGGER_TOKEN}} -F ref=main https://software.nersc.gov/api/v4/projects/307/trigger/pipeline
          args: -X POST -F token=${{secrets.CORI_COMPILE}} -F ref=main https://software.nersc.gov/api/v4/projects/351/trigger/pipeline
